---
title: "Animate Rasters"
author: "Katie Lankowicz"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: pdf_document
header-includes:
    - \usepackage{setspace}\onehalfspacing
    - \usepackage{float}
sansfont: Calibri
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Clear workspace
rm(list=ls())

#### Load libraries ####
library(raster)
library(lubridate)
library(gifski)

# Set seed for reproducibility
set.seed(123)
```

|        This is a bonus instruction on how to animate raster output from IBMs. Adjust the names of the inputs and save locations as necessary.

\singlespacing
```{r, eval=F}
# Load data
load("G:/My Drive/Documents_Backup/Modeling/Modeling_RCode/2022_Apr20_0832.Rdata")

# Set PNG save location
setwd(paste0("G:/My Drive/Documents_Backup/Modeling/Modeling_RCode/",
             "GIFs/sch_mov/subset_Apr20_0832"))

# Initialize progress bar
pb <- txtProgressBar(min=0, max=length(time_steps), initial=0, char="=", style=3)

# Loop through time steps
for(i in 1:time_steps){
  # Initialize timestamp
  if(s==30){
    timest <- "2006-05-31 23:59:30"
  }
  if(s==2){
    timest <- "2006-05-31 23:59:58"
  }

  timest <- as.POSIXct(timest,
                     format="%Y-%m-%d %H:%M:%S", 
                     tz="America/New_York")
  timest <- timest + lubridate::seconds(i*s)
  timest <- gsub(":", "-", timest)
  if(nchar(timest)==10){
    timest <- paste0(timest, " 00-00-00")
  }
  # Open PNG
  png(paste0(timest, ".png"))
  if(s==30){
    # Plot raster for env move
    raster::plot(hsi[[ceiling(i/60/(60/s))]],
                 asp=1,
                 col=cols,
                 xlab="Longitude (m)",
                 ylab="Latitude (m)",
                 zlim=c(minhsi, maxhsi),
                 legend.args=list(text="HSI", side=4, line=2.5),
                 main=paste0(timest))
  }
  if(s==2){
    # Plot raster for sch move
    raster::plot(r,
                 asp=1,
                 col='lightgray',
                 xlab="Longitude (m)",
                 ylab="Latitude (m)",
                 legend=FALSE,
                 main=paste0(timest)
                 )
  }

  # Plot fish
  points(inds_hist[,"x_loc",i],
         inds_hist[,"y_loc",i], 
         pch=19,
         cex=0.25)
  # Close PNG
  dev.off()
  
  # Update progress bar
  setTxtProgressBar(pb, ts)
  getTxtProgressBar(pb)
  # Close segment of progress bar every loop
  close(pb)
}

# List files in given directory
files  <- list.files()
files <- paste0(getwd(), "/", files)

# Set GIF save location
setwd("G:/My Drive/Documents_Backup/Modeling/Modeling_RCode/GIFs/")

# Convert PNGs to GIF
gifski(files, "sch_mov_Apr20_0832.gif", loop = FALSE, delay = 0.01)
```